### ISSUE TITLE
Change size

### ISSUE THREAD

**Issue by iambenmitchell** [vickysvicky/camView#1]
Hi, I am trying to use this project but I cannot see how I would go about changing the size / resolution.

At the moment the view is only a small portion of my screen size

**Comment by vickysvicky** [comment]
Hi Ben! I believe this [link](https://stackoverflow.com/questions/2674375/uiimagepickercontroller-doesnt-fill-screen) will be helpful to you. What you what to do is go into the ViewController.swift in the test file and add or modify  `picker.cameraViewTransform`.
